version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MatchBall@2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MatchBallDb;User=sa;Password=MatchBall@2024!;TrustServerCertificate=True
      - Jwt__Key=MatchBallSuperSecretKey2024!@#$%^&*()
      - Jwt__Issuer=MatchBall
      - Jwt__Audience=MatchBall
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  sqldata:
