FROM node:20-alpine AS build
WORKDIR /app
COPY matchball-client/package*.json ./
RUN npm ci
COPY matchball-client/ .
RUN npm run build

FROM nginx:alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
